from pathlib import Path
p=Path('engines/shared/parity_app.py')
t=p.read_text()
old='''with st.spinner("Fetching current comparison inputs..."):\n    prod_price = prod.fetch_btc_history(start_date, end_date)\n    research_price = research.fetch_btc_history(start_date, end_date)\n    token = prod.get_bgeometrics_token()\n    # One BGeometrics bundle only. Research and Production are not allowed to double-spend quota here.\n    prod_bg = prod.fetch_bgeometrics_bundle(start_date, end_date, token)\n'''
new='''with st.spinner("Fetching current comparison inputs..."):\n    prod_price = prod.fetch_btc_history(start_date, end_date)\n    research_price = research.fetch_btc_history(start_date, end_date)\n    prod_fx = prod.fetch_aud_usd_rates(start_date, end_date)\n    token = prod.get_bgeometrics_token()\n    # One BGeometrics bundle only. Research and Production are not allowed to double-spend quota here.\n    prod_bg = prod.fetch_bgeometrics_bundle(start_date, end_date, token)\n'''
assert old in t
t=t.replace(old,new,1)
start=t.index('st.subheader("2. Central master vs current Production inputs")')
end=t.index('parity = pd.DataFrame(rows)', start)
replacement='''st.subheader("2. Central master vs current Production inputs")\nrows = []\nwindow = central.loc[(central.index.date >= start_date) & (central.index.date <= end_date)]\n\ndef add_or_gap(label, current_series, central_col, current_source):\n    if central_col in window.columns and current_series is not None and len(current_series):\n        rows.append(_comparison_row(label, current_series, window[central_col], current_source, central_col))\n    else:\n        rows.append({\n            "Input": label, "Current source": current_source, "Central candidate": central_col,\n            "Overlap days": 0, "Status": "SOURCE-PRESERVING CENTRAL GAP"\n        })\n\nadd_or_gap(\n    "BTC/USD daily price",\n    prod_price["price"] if (not prod_price.empty and "price" in prod_price.columns) else None,\n    "src__blockchain_btc_usd",\n    "Blockchain.com market-price",\n)\nadd_or_gap(\n    "MVRV Z-Score",\n    prod_bg["mvrv_z"] if "mvrv_z" in prod_bg.columns else None,\n    "src__bgeometrics_mvrv_z",\n    "BGeometrics mvrv-zscore",\n)\nadd_or_gap(\n    "Fear & Greed",\n    prod_bg["fear_greed"] if "fear_greed" in prod_bg.columns else None,\n    "src__bgeometrics_fear_greed",\n    "BGeometrics fear-greed",\n)\nadd_or_gap(\n    "AUD/USD FX",\n    prod_fx if prod_fx is not None else None,\n    "src__frankfurter_usd_per_aud",\n    "Frankfurter business-day FX",\n)\nadd_or_gap(\n    "Regime Score",\n    prod_bg["regime_score"] if "regime_score" in prod_bg.columns else None,\n    "src__bgeometrics_regime_score",\n    "BGeometrics regime-score",\n)\n\nst.caption(\n    "Migration readiness is based only on exact source-preserving `src__` columns. "\n    "Coin Metrics remains useful research data but is not treated as a substitute for the Production Blockchain.com feed."\n)\n\n'''
t=t[:start]+replacement+t[end:]
t=t.replace('gaps = int(parity["Status"].str.contains("GAP|NO VALIDATED", regex=True, na=False).sum())','gaps = int(parity["Status"].str.contains("GAP", regex=True, na=False).sum())')
p.write_text(t)
print('patched parity lab exact sources')
